# Generated by Django 4.0.4 on 2022-07-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tarea',
            new_name='post',
        ),
    ]
